# Generated by Django 4.0.6 on 2024-10-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
